### PR TITLE
Integration of TangoBox 9.2 documentation

### PR DESCRIPTION
**Pull request by piogor**
Preview is available here:
http://tango-controls.readthedocs.io/en/tangobox-documentation/installation/virtualmachine.html
http://tango-controls.readthedocs.io/en/tangobox-documentation/installation/vm/tangobox-9.2.html

### CODE REVIEW

**Comment by andygotz** [comment]
Nice work! One small improvement would be to remove the long title: "Welcome to TangoBox 9.2 - a Tango Controls demo VM’s documentation!" and just call it "TangoBox 9.2"

**Comment by piogor** [comment]
@andygotz, please wait with merge until I add web applications screenshots and more text.

**Comment by piogor** [comment]
Screenshots of web applications are added and texts are implemented. @andygotz , It is now ready to be merged.

**Comment by andygotz** [comment]
Looks good. Can you add a screenshot of jupytango?  I will merge what you have done already.

**Pull request merged**
