### PR TITLE
#299 - tangobox 9.3 on AWS

### PR DESCRIPTION
**Pull request by piogor**

### CODE REVIEW

**Comment by mliszcz** [comment]
As @Ingvord is on vacation, let me merge the PR so that we are not blocked with a release.

**Comment by andygotz** [comment]
Is this the new lighter version of TangoBox on AWS? How can I try it out?

**Comment by piogor** [comment]
@andygotz, it basicaly full TangoBox image,with disk size reduced do 30GB. It has enabled SSH and remote desktop. The documetationis here: https://tango-controls.readthedocs.io/en/latest/installation/amazon-cloud.html.

**Comment by piogor** [comment]
@andygotz , then I have also prepared related news for Tango Controls webpage.

**Comment by andygotz** [comment]
Excellent! I just tested it and it works like a charm - very good work! This provides a very easy way for trying out the full suite of Tango Controls tools! I look forward to testing it on newcomers at the Tango workshop at ICALEPCS 2019.

**Pull request merged**
