### PR TITLE
tango-doc-17

### PR DESCRIPTION
**Pull request by Ingvord**
PR for #17

### CODE REVIEW

**Comment by LJBD** [comment]
IMHO all "api" should be changed to capitals ("API").

**Comment by Ingvord** [comment]
Ready for a review

**Comment by piogor** [comment]
It was merged even it is not linked from anywhere. The linking will be done in a new structure.

**Comment by Ingvord** [comment]
@piogor thanks a lot! 

Minor thought: I would prefer squash and merge to keep master branch history clean

**Comment by piogor** [comment]
@Ingvord, shell I close the branch tango-doc-17?

**Pull request merged**
