### PR TITLE
Td 15 - Bensikin Manual converted

### PR DESCRIPTION
**Pull request by piogor**
The most recent version of the Bensikin Manual has been converted and cleaned (#15). Ready to be merged.
Preview is available here: http://tango-controls.readthedocs.io/en/td-15-bensikin-snap/tools-and-extensions/archiving/bensikin.html

### CODE REVIEW

**Comment by piogor** [comment]
Hi @andygotz, @alainbuteau, @gwen-soleil, if you find time please review Bensikin Manual converted to sphinx before it goes for public. I am planning to merge it by the end of this week.

**Comment by andygotz** [comment]
Looks like a lot of work! The result still looks a bit too much like an internal document. Can you remove the SOLEIL logo and ICA Group too? I would also remove the history of the document. It will now be part of the manual and versions will be managed by git. Replace the history with the names of the authors. I would also remove the Figure Index and start with the Introduction.

Contents of documentation: mention in the documentation that the current version supports only HDB. The difference between Bensikin and SNAP is not clear. Are they the same application? This could be made clearer in the documentation (IMO).

Its place in the documentation is not very clear. We should have it as a sub-element of HDB so readers can see it is part of HDB. 

Andy

**Comment by piogor** [comment]
Thank you @andygotz, I will make corrections. 
I am not sure about placing SNAP related documents under HDB. However it is delivered together with HDB/TDB, it provides separate functionality and can be installed independently. I would rather make a general SNAP related page under `Tools and Extensions` and reference Bensikin Manual from there. What do you think about that?

**Comment by andygotz** [comment]
OK thanks!

**Comment by piogor** [comment]
Following @andygotz and Raphael comments the Bensikin is now under SNAP page and the beginning of the document is updated: http://tango-controls.readthedocs.io/en/td-15-bensikin-snap/tools-and-extensions/archiving/SNAP.html

**Comment by andygotz** [comment]
@piogor  this looks better and is clearer now - thanks!

**Comment by piogor** [comment]
Following @andygotz comments I am mergin the branch.

**Pull request merged**
