### PR TITLE
Td 104  - labelling wiith audience and language

### PR DESCRIPTION
**Pull request by piogor**
Documents are labelled for intended audience and programming language (where applicable). See #104.
It may be previewed here: http://tango-controls.readthedocs.io/en/td-104-audience-and-language/

### CODE REVIEW

**Comment by andygotz** [comment]
Cześć Piotr

sounds like a good idea to have different targets for different audiences but how do I select the target? On the first page I only see Languages as an option. Do I need to go to specific pages?

Andy

**Comment by piogor** [comment]
Hej @andygotz , the colour of the label has been changed to green :).

**Comment by andygotz** [comment]
Hej @piogor thanks! I find it easier to see now. 

I noticed the Copyright is 2017. Shouldn't we change this to 2017-2018?

**Comment by piogor** [comment]
Yes, it is updated, now. So, I am going to merge this to production.

**Pull request merged**
