### PR TITLE
Backport changes from master into 9.3.4

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by t-b** [comment]
@mliszcz Should I just merge?

**Comment by piogor** [comment]
Thanks @t-b ! Before we do backport, we are going to solve warnings we have just introduced ;-).

**Comment by mliszcz** [comment]
@t-b I allowed myself to remove me from the reviewers as I do not track what is going on in tango-doc and I cannot provide any valuable technical feedback here. I hope it will be enough if Piotr will give you a green light once all warnings are fixed. Sorry!

**Comment by t-b** [comment]
Thanks for merging.

**Pull request merged**
